; This config.ini file is used for setup of the Arduino Giga R1 Wifi.
; Copy the file to a USB thumb drive formatted for FAT (also known as 
; MS-DOS).  Insert into the Giga and power it on.  The RGB LED will pulse
; blue until the drive is read.  
;
; If this file parses correctly: the settings will be saved to flash and 
; the LED turns solid blue and the Arduino halts.  Power off the Giga board
; and remove the USB drive.  To prevent the file from accidentally being
; loaded onto another Giga (and creating an IP address collision), the
; file will be renamed to config.ini.S indicating that it has been saved.
;
; If the file is missing a needed setting or is otherwise un-readable: the
; LED will flash blue rapidly in an S-O-S pattern (3 fast, 3 slow, 3 fast).
; To determine what is wrong, plug the USB-C of the Giga board into a 
; computer and use a serial terminal program (such as Putty or Minicom) to 
; see the error output.

[network]
ip = 10.77.0.210
netmask = 255.255.0.0
gateway = 10.77.0.1
dns = 128.171.1.1