; This config.ini file is used for setup of the Arduino Giga R1 Wifi.
; Copy the file to a USB thumb drive formatted for FAT (also known as 
; MS-DOS).  Insert into the Giga and power it on.  The RGB LED will pulse
; blue until the drive is read.  
;
; If this file parses correctly: the settings will be saved to flash and 
; the LED turns solid blue and the Arduino halts.  Power off the Giga board
; and remove the USB drive.  
;
; If the file is missing a needed setting or is otherwise un-readable: the
; LED will flash blue rapidly in an S-O-S pattern (3 fast, 3 slow, 3 fast).
; To determine what is wrong, plug the USB-C of the Giga board into a 
; computer and use a serial terminal program (such as Putty or Minicom) to 
; see the error output.

net.ip = 192.168.78.201
net.netmask = 255.255.255.0
net.gateway = 192.168.78.1
net.dns = 128.171.1.1

sensor.sn = 2633
cal.slope = 0.005587
cal.const = -259.5
