; This config.ini file is used for setup of the Arduino Giga R1 Wifi.
; Copy the file to a USB flash drive formatted for FAT (also known as 
; MS-DOS).  Insert into the Giga and power it on.  
;
; If this file parses correctly the settings will be saved to flash and 
; the LED blinks green at 1Hz.  Power off the Giga board and remove the USB 
; flash drive.  Powering the Giga back on will use the saved settings.
;
; If the file is missing a needed setting, the LED will flash red rapidly.
;
; To determine what is wrong: plug the USB-C of the Giga board into a 
; computer and use a serial terminal program (such as Putty or Minicom) to 
; see the error output.

net.ip = 10.77.0.210
net.netmask = 255.255.0.0
net.gateway = 10.77.0.1
net.dns = 128.171.1.1

; The following settings are placeholders; they will be are used for load cell 
; calibration, which is currently TBD.
cal.coeff1 = 1.0
cal.coeff2 = 2.0
cal.coeff3 = 3.0
